/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as UserRouteImport } from './routes/user'
import { Route as TranscricaoRouteImport } from './routes/transcricao'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as MentoriasRouteImport } from './routes/mentorias'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as GanchosRouteImport } from './routes/ganchos'
import { Route as ExecucoesRouteImport } from './routes/execucoes'
import { Route as EcosistemaRouteImport } from './routes/ecosistema'
import { Route as DocumentacaoRouteImport } from './routes/documentacao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConcorrenteRouteImport } from './routes/concorrente'
import { Route as CentralAjudaRouteImport } from './routes/central-ajuda'
import { Route as CarrosselRouteImport } from './routes/carrossel'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AutomacoesIaRouteImport } from './routes/automacoes-ia'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'
import { Route as ApiPublicIgVideoRouteImport } from './routes/api/public/ig-video'
import { Route as ApiPublicIgThumbRouteImport } from './routes/api/public/ig-thumb'
import { Route as AuthenticatedProjetosViralmindRouteImport } from './routes/_authenticated/projetos/viralmind'
import { Route as ApiPublicHooksSyncMentorshipVideosRouteImport } from './routes/api/public/hooks/sync-mentorship-videos'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscricaoRoute = TranscricaoRouteImport.update({
  id: '/transcricao',
  path: '/transcricao',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriasRoute = MentoriasRouteImport.update({
  id: '/mentorias',
  path: '/mentorias',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GanchosRoute = GanchosRouteImport.update({
  id: '/ganchos',
  path: '/ganchos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecucoesRoute = ExecucoesRouteImport.update({
  id: '/execucoes',
  path: '/execucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosistemaRoute = EcosistemaRouteImport.update({
  id: '/ecosistema',
  path: '/ecosistema',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacaoRoute = DocumentacaoRouteImport.update({
  id: '/documentacao',
  path: '/documentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcorrenteRoute = ConcorrenteRouteImport.update({
  id: '/concorrente',
  path: '/concorrente',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralAjudaRoute = CentralAjudaRouteImport.update({
  id: '/central-ajuda',
  path: '/central-ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrosselRoute = CarrosselRouteImport.update({
  id: '/carrossel',
  path: '/carrossel',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesIaRoute = AutomacoesIaRouteImport.update({
  id: '/automacoes-ia',
  path: '/automacoes-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjetosRoute,
} as any)
const ApiPublicIgVideoRoute = ApiPublicIgVideoRouteImport.update({
  id: '/api/public/ig-video',
  path: '/api/public/ig-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIgThumbRoute = ApiPublicIgThumbRouteImport.update({
  id: '/api/public/ig-thumb',
  path: '/api/public/ig-thumb',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetosViralmindRoute =
  AuthenticatedProjetosViralmindRouteImport.update({
    id: '/_authenticated/projetos/viralmind',
    path: '/projetos/viralmind',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncMentorshipVideosRoute =
  ApiPublicHooksSyncMentorshipVideosRouteImport.update({
    id: '/api/public/hooks/sync-mentorship-videos',
    path: '/api/public/hooks/sync-mentorship-videos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analise': typeof AnaliseRoute
  '/automacoes-ia': typeof AutomacoesIaRoute
  '/blog': typeof BlogRoute
  '/calendario': typeof CalendarioRoute
  '/carrossel': typeof CarrosselRoute
  '/central-ajuda': typeof CentralAjudaRoute
  '/concorrente': typeof ConcorrenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentacao': typeof DocumentacaoRoute
  '/ecosistema': typeof EcosistemaRoute
  '/execucoes': typeof ExecucoesRoute
  '/ganchos': typeof GanchosRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/mentorias': typeof MentoriasRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-somos': typeof QuemSomosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/transcricao': typeof TranscricaoRoute
  '/user': typeof UserRoute
  '/workflows': typeof WorkflowsRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/r/$slug': typeof RSlugRoute
  '/projetos/viralmind': typeof AuthenticatedProjetosViralmindRoute
  '/api/public/ig-thumb': typeof ApiPublicIgThumbRoute
  '/api/public/ig-video': typeof ApiPublicIgVideoRoute
  '/api/public/hooks/sync-mentorship-videos': typeof ApiPublicHooksSyncMentorshipVideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analise': typeof AnaliseRoute
  '/automacoes-ia': typeof AutomacoesIaRoute
  '/blog': typeof BlogRoute
  '/calendario': typeof CalendarioRoute
  '/carrossel': typeof CarrosselRoute
  '/central-ajuda': typeof CentralAjudaRoute
  '/concorrente': typeof ConcorrenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentacao': typeof DocumentacaoRoute
  '/ecosistema': typeof EcosistemaRoute
  '/execucoes': typeof ExecucoesRoute
  '/ganchos': typeof GanchosRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/mentorias': typeof MentoriasRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-somos': typeof QuemSomosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/transcricao': typeof TranscricaoRoute
  '/user': typeof UserRoute
  '/workflows': typeof WorkflowsRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/r/$slug': typeof RSlugRoute
  '/projetos/viralmind': typeof AuthenticatedProjetosViralmindRoute
  '/api/public/ig-thumb': typeof ApiPublicIgThumbRoute
  '/api/public/ig-video': typeof ApiPublicIgVideoRoute
  '/api/public/hooks/sync-mentorship-videos': typeof ApiPublicHooksSyncMentorshipVideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analise': typeof AnaliseRoute
  '/automacoes-ia': typeof AutomacoesIaRoute
  '/blog': typeof BlogRoute
  '/calendario': typeof CalendarioRoute
  '/carrossel': typeof CarrosselRoute
  '/central-ajuda': typeof CentralAjudaRoute
  '/concorrente': typeof ConcorrenteRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/documentacao': typeof DocumentacaoRoute
  '/ecosistema': typeof EcosistemaRoute
  '/execucoes': typeof ExecucoesRoute
  '/ganchos': typeof GanchosRoute
  '/integracoes': typeof IntegracoesRoute
  '/login': typeof LoginRoute
  '/mentorias': typeof MentoriasRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/quem-somos': typeof QuemSomosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suporte': typeof SuporteRoute
  '/termos': typeof TermosRoute
  '/transcricao': typeof TranscricaoRoute
  '/user': typeof UserRoute
  '/workflows': typeof WorkflowsRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/r/$slug': typeof RSlugRoute
  '/_authenticated/projetos/viralmind': typeof AuthenticatedProjetosViralmindRoute
  '/api/public/ig-thumb': typeof ApiPublicIgThumbRoute
  '/api/public/ig-video': typeof ApiPublicIgVideoRoute
  '/api/public/hooks/sync-mentorship-videos': typeof ApiPublicHooksSyncMentorshipVideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analise'
    | '/automacoes-ia'
    | '/blog'
    | '/calendario'
    | '/carrossel'
    | '/central-ajuda'
    | '/concorrente'
    | '/configuracoes'
    | '/documentacao'
    | '/ecosistema'
    | '/execucoes'
    | '/ganchos'
    | '/integracoes'
    | '/login'
    | '/mentorias'
    | '/planos'
    | '/privacidade'
    | '/projetos'
    | '/quem-somos'
    | '/reset-password'
    | '/suporte'
    | '/termos'
    | '/transcricao'
    | '/user'
    | '/workflows'
    | '/projetos/$id'
    | '/r/$slug'
    | '/projetos/viralmind'
    | '/api/public/ig-thumb'
    | '/api/public/ig-video'
    | '/api/public/hooks/sync-mentorship-videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analise'
    | '/automacoes-ia'
    | '/blog'
    | '/calendario'
    | '/carrossel'
    | '/central-ajuda'
    | '/concorrente'
    | '/configuracoes'
    | '/documentacao'
    | '/ecosistema'
    | '/execucoes'
    | '/ganchos'
    | '/integracoes'
    | '/login'
    | '/mentorias'
    | '/planos'
    | '/privacidade'
    | '/projetos'
    | '/quem-somos'
    | '/reset-password'
    | '/suporte'
    | '/termos'
    | '/transcricao'
    | '/user'
    | '/workflows'
    | '/projetos/$id'
    | '/r/$slug'
    | '/projetos/viralmind'
    | '/api/public/ig-thumb'
    | '/api/public/ig-video'
    | '/api/public/hooks/sync-mentorship-videos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analise'
    | '/automacoes-ia'
    | '/blog'
    | '/calendario'
    | '/carrossel'
    | '/central-ajuda'
    | '/concorrente'
    | '/configuracoes'
    | '/documentacao'
    | '/ecosistema'
    | '/execucoes'
    | '/ganchos'
    | '/integracoes'
    | '/login'
    | '/mentorias'
    | '/planos'
    | '/privacidade'
    | '/projetos'
    | '/quem-somos'
    | '/reset-password'
    | '/suporte'
    | '/termos'
    | '/transcricao'
    | '/user'
    | '/workflows'
    | '/projetos/$id'
    | '/r/$slug'
    | '/_authenticated/projetos/viralmind'
    | '/api/public/ig-thumb'
    | '/api/public/ig-video'
    | '/api/public/hooks/sync-mentorship-videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnaliseRoute: typeof AnaliseRoute
  AutomacoesIaRoute: typeof AutomacoesIaRoute
  BlogRoute: typeof BlogRoute
  CalendarioRoute: typeof CalendarioRoute
  CarrosselRoute: typeof CarrosselRoute
  CentralAjudaRoute: typeof CentralAjudaRoute
  ConcorrenteRoute: typeof ConcorrenteRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DocumentacaoRoute: typeof DocumentacaoRoute
  EcosistemaRoute: typeof EcosistemaRoute
  ExecucoesRoute: typeof ExecucoesRoute
  GanchosRoute: typeof GanchosRoute
  IntegracoesRoute: typeof IntegracoesRoute
  LoginRoute: typeof LoginRoute
  MentoriasRoute: typeof MentoriasRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  QuemSomosRoute: typeof QuemSomosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuporteRoute: typeof SuporteRoute
  TermosRoute: typeof TermosRoute
  TranscricaoRoute: typeof TranscricaoRoute
  UserRoute: typeof UserRoute
  WorkflowsRoute: typeof WorkflowsRoute
  RSlugRoute: typeof RSlugRoute
  AuthenticatedProjetosViralmindRoute: typeof AuthenticatedProjetosViralmindRoute
  ApiPublicIgThumbRoute: typeof ApiPublicIgThumbRoute
  ApiPublicIgVideoRoute: typeof ApiPublicIgVideoRoute
  ApiPublicHooksSyncMentorshipVideosRoute: typeof ApiPublicHooksSyncMentorshipVideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcricao': {
      id: '/transcricao'
      path: '/transcricao'
      fullPath: '/transcricao'
      preLoaderRoute: typeof TranscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorias': {
      id: '/mentorias'
      path: '/mentorias'
      fullPath: '/mentorias'
      preLoaderRoute: typeof MentoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ganchos': {
      id: '/ganchos'
      path: '/ganchos'
      fullPath: '/ganchos'
      preLoaderRoute: typeof GanchosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execucoes': {
      id: '/execucoes'
      path: '/execucoes'
      fullPath: '/execucoes'
      preLoaderRoute: typeof ExecucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosistema': {
      id: '/ecosistema'
      path: '/ecosistema'
      fullPath: '/ecosistema'
      preLoaderRoute: typeof EcosistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacao': {
      id: '/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof DocumentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concorrente': {
      id: '/concorrente'
      path: '/concorrente'
      fullPath: '/concorrente'
      preLoaderRoute: typeof ConcorrenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-ajuda': {
      id: '/central-ajuda'
      path: '/central-ajuda'
      fullPath: '/central-ajuda'
      preLoaderRoute: typeof CentralAjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrossel': {
      id: '/carrossel'
      path: '/carrossel'
      fullPath: '/carrossel'
      preLoaderRoute: typeof CarrosselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes-ia': {
      id: '/automacoes-ia'
      path: '/automacoes-ia'
      fullPath: '/automacoes-ia'
      preLoaderRoute: typeof AutomacoesIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/api/public/ig-video': {
      id: '/api/public/ig-video'
      path: '/api/public/ig-video'
      fullPath: '/api/public/ig-video'
      preLoaderRoute: typeof ApiPublicIgVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ig-thumb': {
      id: '/api/public/ig-thumb'
      path: '/api/public/ig-thumb'
      fullPath: '/api/public/ig-thumb'
      preLoaderRoute: typeof ApiPublicIgThumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projetos/viralmind': {
      id: '/_authenticated/projetos/viralmind'
      path: '/projetos/viralmind'
      fullPath: '/projetos/viralmind'
      preLoaderRoute: typeof AuthenticatedProjetosViralmindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-mentorship-videos': {
      id: '/api/public/hooks/sync-mentorship-videos'
      path: '/api/public/hooks/sync-mentorship-videos'
      fullPath: '/api/public/hooks/sync-mentorship-videos'
      preLoaderRoute: typeof ApiPublicHooksSyncMentorshipVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjetosRouteChildren {
  ProjetosIdRoute: typeof ProjetosIdRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosIdRoute: ProjetosIdRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnaliseRoute: AnaliseRoute,
  AutomacoesIaRoute: AutomacoesIaRoute,
  BlogRoute: BlogRoute,
  CalendarioRoute: CalendarioRoute,
  CarrosselRoute: CarrosselRoute,
  CentralAjudaRoute: CentralAjudaRoute,
  ConcorrenteRoute: ConcorrenteRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DocumentacaoRoute: DocumentacaoRoute,
  EcosistemaRoute: EcosistemaRoute,
  ExecucoesRoute: ExecucoesRoute,
  GanchosRoute: GanchosRoute,
  IntegracoesRoute: IntegracoesRoute,
  LoginRoute: LoginRoute,
  MentoriasRoute: MentoriasRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  QuemSomosRoute: QuemSomosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuporteRoute: SuporteRoute,
  TermosRoute: TermosRoute,
  TranscricaoRoute: TranscricaoRoute,
  UserRoute: UserRoute,
  WorkflowsRoute: WorkflowsRoute,
  RSlugRoute: RSlugRoute,
  AuthenticatedProjetosViralmindRoute: AuthenticatedProjetosViralmindRoute,
  ApiPublicIgThumbRoute: ApiPublicIgThumbRoute,
  ApiPublicIgVideoRoute: ApiPublicIgVideoRoute,
  ApiPublicHooksSyncMentorshipVideosRoute:
    ApiPublicHooksSyncMentorshipVideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
